server:
  port: 8082

spring:
  application:
    name: code-analyzer

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/codeguardian
    username: ${DB_USERNAME:codeguardian}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
    consumer:
      group-id: code-analyzer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

# Analysis Configuration
analysis:
  security:
    enabled: true
    rules:
      - hardcoded_secret
      - sql_injection
      - xss_vulnerability
      - weak_crypto
      - insecure_random
  quality:
    enabled: true
    complexity-threshold: 10
    method-length-threshold: 50
  compliance:
    enabled: true
    frameworks:
      - PCI-DSS
      - GDPR
      - HIPAA
      - SOX
      - OWASP

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    com.codeguardian: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Custom Application Properties
app:
  kafka:
    topics:
      commit-analysis: commit-analysis
      pull-request-analysis: pull-request-analysis
      merge-request-analysis: merge-request-analysis
      analysis-results: analysis-results
  analysis:
    parallel-processing: true
    max-threads: 10
    timeout-seconds: 300