spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        
  kafka:
    bootstrap-servers: localhost:9092

# Test Configuration
analysis:
  security:
    enabled: false
  quality:
    enabled: false
  compliance:
    enabled: false

logging:
  level:
    com.codeguardian: INFO
    org.springframework.kafka: WARN