server:
  port: 8081

spring:
  application:
    name: git-processor
  datasource:
    url: jdbc:postgresql://postgres:5432/codeguardian
    username: ${DB_USERNAME:codeguardian}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

webhook:
  github:
    secret: ${GITHUB_WEBHOOK_SECRET:your-github-webhook-secret}
  gitlab:
    token: ${GITLAB_WEBHOOK_TOKEN:your-gitlab-webhook-token}

logging:
  level:
    com.codeguardian: DEBUG